services:
  - type: web
    name: financer-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13